install.packages("devtools")
install.packages("RPostgres")
install.packages("ggplot2")
devtools::install_github("RcppCore/Rcpp")
devtools::install_github("rstats-db/DBI")
devtools::install_github("rstats-db/RPostgres")
